# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations
compression-level = 9         # compression level for module zips. between 1 and 9
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1             # max number of concurrent building jobs
build-mindetach-module = false

# extended
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"

[YouTube]
build-mode = "both"
excluded-patches = "custom-seekbar-color custom-video-speed default-video-speed disable-haptic-feedback enable-tablet-miniplayer enable-wide-searchbar force-vp9-codec hide-auto-captions hide-autoplay-button hide-captions-button hide-collapse-button hide-comment-component hide-mix-playlists hide-endscreen-cards hide-endscreen-overlay hide-filmstrip-overlay hide-fullscreen-buttoncontainer hide-fullscreen-panels hide-info-cards hide-live-chat-button hide-next-prev-button hide-player-button-background hide-player-overlay-filter hide-seekbar hide-snackbar layout-switch swipe-controls"
included-patches = "client-spoof custom-branding-icon-afn-red custom-branding-name default-video-quality enable-external-browser enable-minimized-playback enable-old-layout enable-old-quality-layout enable-open-links-directly enable-seekbar-tapping force-premium-heading header-switch hide-auto-player-popup-panels hide-button-container hide-channel-watermark hide-create-button hide-crowdfunding-box hide-flyout-panel hide-general-ads hide-mix-playlists hide-shorts-button hide-shorts-component hide-stories hide-video-ads microg-support optimize-resource overlay-buttons patch-options return-youtube-dislike settings sponsorblock theme"
version = "auto"
exclusive-patches = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music-arm64]
enabled=false
build-mode = "none"
app-name = "Music"
excluded-patches = ""
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[Music-arm]
enabled=false
build-mode = "none"
app-name = "Music"
excluded-patches = ""
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm-v7a"
